require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

HashSyntax:
  EnforcedStyle: ruby19

AllCops:
  TargetRubyVersion: 2.7.2

Documentation:
  Enabled: false

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: AllowDoxygenCommentStyle, AllowGemfileRubyComment.
Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'
    - 'spec/models/user_spec.rb'
    - 'spec/requests/food_records_request_spec.rb'

# Offense count: 1
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 19

# Offense count: 4
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 210

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 10

# Offense count: 2
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 20

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 11

# Offense count: 1
# Cop supports --auto-correct.
Rails/ActiveRecordAliases:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

# Offense count: 6
# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/development.rb'
    - 'spec/factories/food_record.rb'
    - 'spec/rails_helper.rb'
    - 'spec/requests/food_records_request_spec.rb'
    - 'spec/factories/food_share.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/CaseLikeIf:
  Exclude:
    - 'app/helpers/food_record_helper.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/confirmations_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/users/unlocks_controller.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

# Offense count: 53
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'app/helpers/food_record_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/uploaders/image_uploader.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/StringConcatenation:
  Exclude:
    - 'app/helpers/food_record_helper.rb'

# Offense count: 94
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 173

# Offense count: 2
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'app/controllers/food_records_controller.rb'
    - 'app/controllers/tags_controller.rb'

# Offense count: 1
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 29

# Offense count: 4
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/food_records_controller.rb'
    - 'app/controllers/tags_controller.rb'
    - 'db/migrate/20201223110713_change_collation_for_tag_names.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20201223110714_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'db/migrate/20201223110713_change_collation_for_tag_names.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20201223110714_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb'

# Offense count: 2
Lint/UselessAssignment:
  Exclude:
    - 'spec/requests/tag_request_spec.rb'
    - 'spec/requests/food_records_request_spec.rb'

# Offense count: 15
# Configuration parameters: EnforcedStyle, CheckMethodNames, CheckSymbols, AllowedIdentifiers.
# SupportedStyles: snake_case, normalcase, non_integer
# AllowedIdentifiers: capture3, iso8601, rfc1123_date, rfc822, rfc2822, rfc3339
Naming/VariableNumber:
  Exclude:
    - 'spec/requests/food_records_request_spec.rb'

# Offense count: 2
# Configuration parameters: Database, Include.
# SupportedDatabases: mysql, postgresql
# Include: db/migrate/*.rb
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20210101084208_remove_time_from_food_share.rb'
    - 'db/migrate/20210101085241_add_date_time_to_food_shares.rb'
    - 'db/migrate/20210118145623_add_column_food_records.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/EmptyLines:
  Exclude:
    - 'db/migrate/20201230094623_create_food_shares.rb'
    - 'db/migrate/20210104064312_create_relationships.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: app/helpers/**/*.rb
Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/InverseOf:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: ConvertCodeThatCanStartToReturnNil, AllowedMethods.
# AllowedMethods: present?, blank?, presence, try, try!
Style/SafeNavigation:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/migrate/20210104064312_create_relationships.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/20210116091805_add_location_id_to_users.rb'

Metrics/ClassLength:
  Max: 120
